# Generated by Django 2.1.7 on 2019-04-04 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_tipo', models.CharField(blank=True, choices=[('IM', 'Implante'), ('PL', 'Placa')], default='PL', max_length=2, null=True, verbose_name='tipo')),
                ('identificacion_ubicacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='ubicacion')),
                ('identificacion_codigo', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='codigo')),
                ('fecha_implante', models.DateField(auto_now_add=True, verbose_name='fecha implante')),
            ],
            options={
                'verbose_name_plural': 'identificaciones',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascota_nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('mascota_sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=2, verbose_name='Sexo')),
                ('fecha_nacimiento_mascota', models.DateField(verbose_name='fecha de nacimiento')),
                ('mascota_color', models.CharField(max_length=20, verbose_name='Color')),
                ('fecha_ultima_vacunacion', models.DateField(verbose_name='fecha de ultima vacunacion')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=30, null=True, verbose_name='DNI')),
                ('es_veterinario', models.BooleanField(default=False, null=True, verbose_name='estado veterinario')),
                ('tiene_lectora', models.BooleanField(default=False, null=True, verbose_name='tiene lectora')),
                ('calle_veterinaria', models.CharField(max_length=30, null=True)),
                ('numero_calle_veterinaria', models.PositiveIntegerField(null=True)),
                ('localidad_veterinaria', models.CharField(max_length=30, null=True)),
                ('provincia_veterinaria', models.CharField(max_length=30, null=True)),
                ('nombre_veterinaria', models.CharField(max_length=30, null=True)),
                ('telefono_veterinaria', models.CharField(max_length=15, null=True)),
                ('telefono_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza_nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota_nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tipo de mascota',
                'verbose_name_plural': 'tipo de mascotas',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='mascota_raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivopetsite.Raza', verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='mascota_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivopetsite.Tipo_Mascota', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivopetsite.Propietario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archivopetsite.Mascota'),
        ),
    ]
