# Generated by Django 2.1.7 on 2019-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='mascota',
            name='senias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tratamientos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
