# Generated by Django 2.1.7 on 2019-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0002_auto_20190416_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cp_veterinaria',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='senias',
            field=models.TextField(blank=True, null=True, verbose_name='Señas'),
        ),
    ]
