# Generated by Django 2.1.7 on 2019-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0003_auto_20190610_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacion',
            name='identificacion_codigo',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='codigo'),
        ),
    ]
