# Generated by Django 2.1.7 on 2019-06-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0004_auto_20190612_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='raza_nombre',
            field=models.CharField(max_length=35),
        ),
    ]
