# Generated by Django 2.1.7 on 2019-06-26 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0005_auto_20190613_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_mascota',
            options={'verbose_name': 'especie de mascota', 'verbose_name_plural': 'especie de mascotas'},
        ),
        migrations.AddField(
            model_name='profile',
            name='establecimiento_tipo',
            field=models.CharField(choices=[('MU', 'Municipalidad'), ('CR', 'Criadero'), ('VT', 'Veterinaria'), ('OT', 'Otro')], default='VT', max_length=2, verbose_name='Tipo Establecimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='identificacion_codigo',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Sólo se permiten números y letras.')], verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='mascota_nombre',
            field=models.CharField(help_text='Ingrese APELLIDO y NOMBRE', max_length=20, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='mascota_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivopetsite.Tipo_Mascota', verbose_name='Especie'),
        ),
    ]
