# Generated by Django 2.1.7 on 2019-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivopetsite', '0006_auto_20190626_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calle_veterinaria',
            field=models.CharField(max_length=30, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='establecimiento_tipo',
            field=models.CharField(choices=[('MU', 'Municipalidad'), ('CR', 'Criadero'), ('VT', 'Veterinaria'), ('PR', 'Protectora'), ('RF', 'Refugio'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo Establecimiento'),
        ),
    ]
